/** Keys match CSS custom properties on `:root` (include `--` prefix). */
export const DESIGN_TOKEN_META: { key: `--${string}`; label: string }[] = [
  { key: '--ds-font-body', label: 'Font · body' },
  { key: '--ds-font-mono', label: 'Font · mono / labels' },
  { key: '--border-medium-dark', label: 'Color · border / divider (medium dark)' },
  { key: '--ds-color-bg', label: 'Color · page background' },
  { key: '--ds-color-surface', label: 'Color · surface' },
  { key: '--ds-color-surface2', label: 'Color · surface muted' },
  { key: '--ds-color-text', label: 'Color · text' },
  { key: '--ds-color-text-muted', label: 'Color · text muted' },
  { key: '--ds-color-text-faint', label: 'Color · text faint' },
  { key: '--ds-color-accent', label: 'Color · primary / submit (green1)' },
  { key: '--ds-color-accent-text', label: 'Color · primary text on light' },
  { key: '--ds-color-accent-light', label: 'Color · primary tint bg' },
  { key: '--ds-color-secondary', label: 'Color · secondary (amber1)' },
  { key: '--ds-color-secondary-text', label: 'Color · secondary text' },
  { key: '--ds-color-secondary-light', label: 'Color · secondary tint bg' },
  { key: '--ds-color-secondary-border', label: 'Color · secondary border' },
  { key: '--ds-color-strip-drawer', label: 'Color · drawer strip (amber)' },
  { key: '--ds-color-strip-drawer-strong', label: 'Color · drawer strip strong' },
  { key: '--ds-color-strip-drawer-light', label: 'Color · drawer strip tint' },
  { key: '--ds-color-strip-drawer-border', label: 'Color · drawer strip border' },
  { key: '--ds-color-strip-drawer-text', label: 'Color · drawer strip text' },
  { key: '--ds-color-danger', label: 'Color · danger' },
]

export const DEFAULT_DESIGN_TOKENS: Record<string, string> = {
  '--border-medium-dark': '#CFCFCF',
  '--ds-font-body': 'var(--font-sans)',
  '--ds-font-mono': 'var(--font-mono)',
  '--ds-color-bg': '#F9F9F9',
  '--ds-color-surface': '#ffffff',
  '--ds-color-surface2': '#E8EDF2',
  '--ds-color-text': '#1A2332',
  '--ds-color-text-muted': '#5F5E5A',
  '--ds-color-text-faint': '#888780',
  '--ds-color-accent': '#0F9544',
  '--ds-color-accent-text': '#1A5C3D',
  '--ds-color-accent-light': '#D4F9E4',
  '--ds-color-secondary': '#F9A03F',
  '--ds-color-secondary-text': '#6B5410',
  '--ds-color-secondary-light': '#FEF3E0',
  '--ds-color-secondary-border': 'rgba(249, 160, 63, 0.42)',
  '--ds-color-strip-drawer': '#F9A03F',
  '--ds-color-strip-drawer-strong': '#B87A2E',
  '--ds-color-strip-drawer-light': '#FEF3E0',
  '--ds-color-strip-drawer-border': 'rgba(249, 160, 63, 0.42)',
  '--ds-color-strip-drawer-text': '#6B5410',
  '--ds-color-danger': '#C03221',
}

export const DESIGN_STORAGE_KEY = 'retirement-calc-design-tokens'
