import type { LifeEventConfig } from './types'

const y = (offset: number) => (currentYear: number, retirementYear: number) =>
  Math.min(currentYear + offset, retirementYear)

export const LIFE_EVENT_CONFIGS: LifeEventConfig[] = [
  {
    id: 'buy-car-cash',
    group: 'capital-decisions',
    direction: 'outflow',
    title: 'Buy a car with cash',
    instanceNoun: 'vehicles',
    supportsMultiple: true,
    labelPlaceholder: 'e.g. 2027 SUV',
    addInstanceLabel: '+ Add vehicle',
    defaultAmount: 35000,
    defaultYear: y(1),
    amountMin: 5000,
    amountMax: 150000,
    amountStep: 1000,
    amountLabel: 'Purchase price',
    yearLabel: 'When to purchase?',
    color: '#EF9F27',
  },
  {
    id: 'pay-off-mortgage',
    group: 'capital-decisions',
    direction: 'outflow',
    title: 'Pay off mortgage early',
    instanceNoun: 'mortgages',
    supportsMultiple: true,
    labelPlaceholder: 'e.g. Primary home',
    addInstanceLabel: '+ Add mortgage',
    defaultAmount: 85000,
    defaultYear: y(2),
    amountMin: 10000,
    amountMax: 600000,
    amountStep: 5000,
    amountLabel: 'Remaining balance',
    yearLabel: 'When to pay off?',
    color: '#E24B4A',
  },
  {
    id: 'pay-student-loans',
    group: 'capital-decisions',
    direction: 'outflow',
    title: 'Pay off student loans early',
    instanceNoun: 'loans',
    supportsMultiple: true,
    labelPlaceholder: 'e.g. Federal loans',
    addInstanceLabel: '+ Add loan',
    defaultAmount: 45000,
    defaultYear: y(2),
    amountMin: 1000,
    amountMax: 300000,
    amountStep: 1000,
    amountLabel: 'Remaining balance',
    yearLabel: 'When to pay off?',
    color: '#E24B4A',
  },
  {
    id: 'buy-vacation-property',
    group: 'capital-decisions',
    direction: 'outflow',
    title: 'Buy a second property or vacation home',
    instanceNoun: 'properties',
    supportsMultiple: true,
    labelPlaceholder: 'e.g. Beach house',
    addInstanceLabel: '+ Add property',
    defaultAmount: 350000,
    defaultYear: y(2),
    amountMin: 50000,
    amountMax: 2000000,
    amountStep: 10000,
    amountLabel: 'Purchase price',
    yearLabel: 'Year of purchase',
    color: '#185FA5',
  },
  {
    id: 'child-down-payment',
    group: 'capital-decisions',
    direction: 'outflow',
    title: 'Help a child with a down payment',
    instanceNoun: 'gifts',
    supportsMultiple: true,
    labelPlaceholder: 'e.g. Down payment help — Sara',
    addInstanceLabel: '+ Add gift',
    defaultAmount: 50000,
    defaultYear: y(3),
    amountMin: 5000,
    amountMax: 500000,
    amountStep: 5000,
    amountLabel: 'Gift amount',
    yearLabel: 'When to give?',
    color: '#0F6E56',
  },
  {
    id: 'fund-529',
    group: 'capital-decisions',
    direction: 'outflow',
    title: 'Fund a 529 — lump sum',
    instanceNoun: 'contributions',
    supportsMultiple: true,
    labelPlaceholder: "e.g. Emma's college",
    addInstanceLabel: '+ Add contribution',
    defaultAmount: 25000,
    defaultYear: y(1),
    amountMin: 1000,
    amountMax: 500000,
    amountStep: 1000,
    amountLabel: 'Contribution amount',
    yearLabel: 'When to contribute?',
    color: '#534AB7',
  },
  {
    id: 'wedding',
    group: 'capital-decisions',
    direction: 'outflow',
    title: 'Pay for a wedding — your lump sum contribution',
    instanceNoun: 'weddings',
    supportsMultiple: true,
    labelPlaceholder: "e.g. Jake's wedding",
    addInstanceLabel: '+ Add wedding',
    defaultAmount: 35000,
    defaultYear: y(2),
    amountMin: 5000,
    amountMax: 200000,
    amountStep: 1000,
    amountLabel: 'Lump sum contribution',
    yearLabel: 'When?',
    color: '#D85A30',
  },
  {
    id: 'business-investment',
    group: 'capital-decisions',
    direction: 'outflow',
    title: 'Invest in a business',
    instanceNoun: 'investments',
    supportsMultiple: false,
    labelPlaceholder: '',
    addInstanceLabel: '',
    defaultAmount: 100000,
    defaultYear: y(1),
    amountMin: 5000,
    amountMax: 1000000,
    amountStep: 5000,
    amountLabel: 'Investment amount',
    yearLabel: 'When to invest?',
    color: '#0F6E56',
  },
  {
    id: 'home-renovation',
    group: 'capital-decisions',
    direction: 'outflow',
    title: 'Major home renovation — lump sum',
    instanceNoun: 'renovations',
    supportsMultiple: false,
    labelPlaceholder: '',
    addInstanceLabel: '',
    defaultAmount: 45000,
    defaultYear: y(1),
    amountMin: 5000,
    amountMax: 300000,
    amountStep: 2500,
    amountLabel: 'Renovation amount',
    yearLabel: 'When to renovate?',
    color: '#534AB7',
  },
  {
    id: 'medical-expense',
    group: 'unexpected-hits',
    direction: 'outflow',
    title: 'Major medical expense',
    instanceNoun: 'expenses',
    supportsMultiple: false,
    labelPlaceholder: '',
    addInstanceLabel: '',
    defaultAmount: 25000,
    defaultYear: y(1),
    amountMin: 1000,
    amountMax: 500000,
    amountStep: 1000,
    amountLabel: 'Estimated expense',
    yearLabel: 'When to plan for?',
    color: '#D85A30',
  },
  {
    id: 'home-repair',
    group: 'unexpected-hits',
    direction: 'outflow',
    title: 'Major home repair',
    instanceNoun: 'repairs',
    supportsMultiple: false,
    labelPlaceholder: '',
    addInstanceLabel: '',
    defaultAmount: 15000,
    defaultYear: y(1),
    amountMin: 1000,
    amountMax: 200000,
    amountStep: 500,
    amountLabel: 'Repair amount',
    yearLabel: 'When?',
    color: '#534AB7',
  },
  {
    id: 'family-crisis',
    group: 'unexpected-hits',
    direction: 'outflow',
    title: 'Support a family member in crisis — one-time',
    instanceNoun: 'supports',
    supportsMultiple: false,
    labelPlaceholder: '',
    addInstanceLabel: '',
    defaultAmount: 10000,
    defaultYear: y(1),
    amountMin: 500,
    amountMax: 250000,
    amountStep: 500,
    amountLabel: 'Amount',
    yearLabel: 'When?',
    color: '#534AB7',
  },
  {
    id: 'divorce',
    group: 'unexpected-hits',
    direction: 'outflow',
    title: 'Divorce — asset split',
    instanceNoun: 'splits',
    supportsMultiple: false,
    labelPlaceholder: '',
    addInstanceLabel: '',
    defaultAmount: 150000,
    defaultYear: y(2),
    amountMin: 0,
    amountMax: 5000000,
    amountStep: 5000,
    amountLabel: 'Estimated split',
    yearLabel: 'When?',
    color: '#E24B4A',
  },
  {
    id: 'inheritance',
    group: 'windfalls',
    direction: 'inflow',
    title: 'Inheritance received',
    instanceNoun: 'inheritances',
    supportsMultiple: true,
    labelPlaceholder: 'e.g. From parents',
    addInstanceLabel: '+ Add inheritance',
    defaultAmount: 200000,
    defaultYear: y(3),
    amountMin: 1000,
    amountMax: 5000000,
    amountStep: 5000,
    amountLabel: 'Expected amount',
    yearLabel: 'Year received',
    color: '#1D9E75',
  },
  {
    id: 'sell-business',
    group: 'windfalls',
    direction: 'inflow',
    title: 'Sell a business',
    instanceNoun: 'sales',
    supportsMultiple: false,
    labelPlaceholder: '',
    addInstanceLabel: '',
    defaultAmount: 500000,
    defaultYear: y(5),
    amountMin: 10000,
    amountMax: 10000000,
    amountStep: 10000,
    amountLabel: 'Sale amount',
    yearLabel: 'Year of sale',
    color: '#1D9E75',
  },
  {
    id: 'sell-property',
    group: 'windfalls',
    direction: 'inflow',
    title: 'Sell a property',
    instanceNoun: 'properties',
    supportsMultiple: true,
    labelPlaceholder: 'e.g. Rental property',
    addInstanceLabel: '+ Add property',
    defaultAmount: 400000,
    defaultYear: y(4),
    amountMin: 10000,
    amountMax: 5000000,
    amountStep: 10000,
    amountLabel: 'Sale amount',
    yearLabel: 'Year of sale',
    color: '#1D9E75',
  },
  {
    id: 'pension-lump-sum',
    group: 'windfalls',
    direction: 'inflow',
    title: 'Pension buyout or severance lump sum',
    instanceNoun: 'lump sums',
    supportsMultiple: false,
    labelPlaceholder: '',
    addInstanceLabel: '',
    defaultAmount: 150000,
    defaultYear: y(2),
    amountMin: 5000,
    amountMax: 2000000,
    amountStep: 5000,
    amountLabel: 'Gross amount',
    yearLabel: 'Year received',
    color: '#1D9E75',
  },
]

export function getLifeEventConfig(configId: string): LifeEventConfig | undefined {
  return LIFE_EVENT_CONFIGS.find((c) => c.id === configId)
}

/** @deprecated Use LIFE_EVENT_CONFIGS */
export const growthEventConfigs = LIFE_EVENT_CONFIGS
