/** US city → two-letter state/DC abbreviation for income harvest city labels. */
const US_CITY_STATE_ABBR: Record<string, string> = {
  Albany: 'NY',
  Albuquerque: 'NM',
  Amarillo: 'TX',
  Anchorage: 'AK',
  'Ann Arbor': 'MI',
  Arlington: 'TX',
  Asheville: 'NC',
  Atlanta: 'GA',
  Augusta: 'GA',
  Austin: 'TX',
  Aventura: 'FL',
  Bakersfield: 'CA',
  Baltimore: 'MD',
  Bellevue: 'WA',
  Bend: 'OR',
  Berkeley: 'CA',
  Birmingham: 'AL',
  'Blue Island': 'IL',
  Boise: 'ID',
  Boston: 'MA',
  Brooklyn: 'NY',
  Buffalo: 'NY',
  Charleston: 'SC',
  Charlotte: 'NC',
  Charlottesville: 'VA',
  Chattanooga: 'TN',
  Chicago: 'IL',
  Cincinnati: 'OH',
  Cleveland: 'OH',
  'College Station': 'TX',
  'Colorado Springs': 'CO',
  Columbus: 'OH',
  Dallas: 'TX',
  'Daytona Beach': 'FL',
  Denver: 'CO',
  Detroit: 'MI',
  Durham: 'NC',
  'El Paso': 'TX',
  Eugene: 'OR',
  Everett: 'WA',
  Fairfax: 'VA',
  Fargo: 'ND',
  'Fort Lauderdale': 'FL',
  'Fort Myers': 'FL',
  'Fort Wayne': 'IN',
  'Fort Worth': 'TX',
  Fremont: 'CA',
  Fresno: 'CA',
  Gainesville: 'FL',
  'Grand Rapids': 'MI',
  Greensboro: 'NC',
  Greenville: 'SC',
  Honolulu: 'HI',
  Houston: 'TX',
  'Huntington Beach': 'CA',
  Huntsville: 'AL',
  Indianapolis: 'IN',
  Irvine: 'CA',
  Jacksonville: 'FL',
  'Jersey City': 'NJ',
  Knoxville: 'TN',
  Lancaster: 'PA',
  'Las Vegas': 'NV',
  Lexington: 'KY',
  'Little Rock': 'AR',
  'Long Beach': 'CA',
  'Los Angeles': 'CA',
  Louisville: 'KY',
  Madison: 'WI',
  Memphis: 'TN',
  Mesa: 'AZ',
  Miami: 'FL',
  Milwaukee: 'WI',
  Minneapolis: 'MN',
  Missoula: 'MT',
  Mobile: 'AL',
  Modesto: 'CA',
  'Myrtle Beach': 'SC',
  Nashville: 'TN',
  'New Haven': 'CT',
  'New Orleans': 'LA',
  'New York': 'NY',
  Oakland: 'CA',
  'Oklahoma City': 'OK',
  Olympia: 'WA',
  Omaha: 'NE',
  Orlando: 'FL',
  'Palm Springs': 'CA',
  Pensacola: 'FL',
  Philadelphia: 'PA',
  Phoenix: 'AZ',
  Pittsburgh: 'PA',
  Plano: 'TX',
  'Port St. Lucie': 'FL',
  Portland: 'OR',
  Raleigh: 'NC',
  Reno: 'NV',
  Richmond: 'VA',
  Riverside: 'CA',
  Rochester: 'NY',
  Sacramento: 'CA',
  Salem: 'OR',
  'Salt Lake City': 'UT',
  'San Diego': 'CA',
  'San Jose': 'CA',
  Sarasota: 'FL',
  Savannah: 'GA',
  Seattle: 'WA',
  Spokane: 'WA',
  Springfield: 'MO',
  Sunnyvale: 'CA',
  Syracuse: 'NY',
  Tacoma: 'WA',
  Tallahassee: 'FL',
  Tampa: 'FL',
  Toledo: 'OH',
  Tucson: 'AZ',
  Tulsa: 'OK',
  'Virginia Beach': 'VA',
  Washington: 'DC',
  Wichita: 'KS',
}

export function getUsCityStateAbbr(city: string): string | undefined {
  return US_CITY_STATE_ABBR[city]
}
